version: "3.8"
networks:
  workmotion:
    driver: bridge

services:
  employee:
    container_name: employee-state-machine
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8080:8080"
    networks: 
      - workmotion
    volumes:
            - ./target/:/workmotion/