version: "3"
networks:
  workmotion:
    driver: bridge

services:
  employee:
    container_name: employee-state-machine
    build:
      context: .
    restart: on-failure
    ports:
      - "80:8080"
    networks: 
      - workmotion
    volumes:
            - ./target/:/workmotion/